### ISSUE TITLE
The MSEloss formula in paper

### ISSUE THREAD

**Issue by HHCorp** [fdbtrs/PocketNet#4]
First, thanks for your impressive work. I have a small question about the MSEloss formula in your paper. why there is a '1 -' in the formula?
![image](https://user-images.githubusercontent.com/32769636/162146731-1af7841d-bd2c-4e31-97fa-c0b9960fa20e.png)

**Comment by fdbtrs** [comment]
Thank you for your comment. It is a typo mistake in the paper and we will correct it directly. However, the reported results (in the paper) and the provided training are correct. All results in the paper can be reproduced using the provided code and the pre-trained models.

**Comment by HHCorp** [comment]
> 

I guessed this is a mistake. Thanks for your reply. The results are reproducible.
