### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by HamDan1999** [fdbtrs/PocketNet#8]
Firstly, I really admire all your works (PocketNet, QuantFace, MixFaceNets).

I have a concern, the inference time is extremely slow (even with GPU support), any suggestions on how to make it faster?

Thanks!

**Comment by fdbtrs** [comment]
Could you please be more specific about the term "slow", PocketNet is 6x faster than for example resent100 on CPU

**Comment by fdbtrs** [comment]
you don't need a for loop to load the weight. This is only required if you evaluate all training epochs. Instead, just load the last epoch weights.

**Comment by HamDan1999** [comment]
Noted with thanks!
